### ISSUE TITLE
UsrClass.dat haven't been copied

### ISSUE THREAD

**Issue by mnrkbys** [mgreen27/Invoke-LiveResponse#34]
I have found another issue about the subject.

The code below in sbUser.ps1 has incorrect filename (UserClass.dat).
```
Copy-LiveResponse -path "$profile\AppData\Local\Microsoft\Windows" -dest "$out\AppData\Local\Microsoft\Windows" -filter "UserClass.dat" -forensic
```
It should be "UsrClass.dat".
And, I think the transaction files of UsrClass.dat registry (UsrClass.dat.LOG1 and .LOG2) should be copied too.

**Comment by mgreen27** [comment]
This is fixed in this PR https://github.com/mgreen27/Invoke-LiveResponse/commit/db048ca14f3e9172c6c0d190a58778882685aef3

I didn't include the transaction files in the base sbUser.ps1 but included in sbPlasoFilter.ps1. The idea of the platform is enable a modular capability users can modify their own ScriptBlocks as required. Feel free to submit pull requests!

I will eventually complete some documentation for this too :)
